auditLevel: "high"
blockExoticSubdeps: true
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeStrict: true
nodeLinker: "isolated"
preferFrozenLockfile: true
preferOffline: false
resolvePeersFromWorkspaceRoot: true
strictPeerDependencies: true
trustPolicy: "no-downgrade"
trustPolicyIgnoreAfter: 43200 # 30 days

packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/react": "19.2.6"
  react: "19.2.6"
  react-native: "0.85.3"
  typescript: "5.9.3"

minimumReleaseAgeExclude:
  - "@expo/cli@56.1.11"
  - "@expo/config-plugins@56.0.8"
  - "@expo/config-types@56.0.5"
  - "@expo/config@56.0.9"
  - "@expo/env@2.3.0"
  - "@expo/fingerprint@0.19.2"
  - "@expo/image-utils@0.10.1"
  - "@expo/inline-modules@0.0.9"
  - "@expo/json-file@10.2.0"
  - "@expo/local-build-cache-provider@56.0.7"
  - "@expo/log-box@56.0.12"
  - "@expo/metro-config@56.0.12"
  - "@expo/metro-runtime@56.0.12"
  - "@expo/osascript@2.6.0"
  - "@expo/package-manager@1.12.0"
  - "@expo/plist@0.7.0"
  - "@expo/prebuild-config@56.0.12"
  - "@expo/require-utils@56.1.3"
  - "@expo/router-server@56.0.11"
  - "@expo/spawn-async@1.8.0"
  - "@expo/ui@56.0.13"
  - babel-preset-expo@56.0.12
  - expo-asset@56.0.14
  - expo-constants@56.0.15
  - expo-file-system@56.0.7
  - expo-font@56.0.5
  - expo-image@56.0.9
  - expo-linking@56.0.11
  - expo-modules-autolinking@56.0.12
  - expo-modules-core@56.0.12
  - expo-modules-jsi@56.0.7
  - expo-router@56.2.6
  - expo-server@56.0.4
  - expo-splash-screen@56.0.10
  - expo-system-ui@56.0.5
  - expo-web-browser@56.0.5
  - expo@56.0.4
  - react-native-screens@4.25.2
  - expo-dev-client@56.0.15
  - expo-dev-launcher@56.0.15
  - expo-dev-menu@56.0.14
  - expo-manifests@56.0.4

allowBuilds:
  msgpackr-extract: true
